name: Print message

on:
  workflow_call:
    inputs:
      message:
        required: true
        type: string
      provider:
        required: true
        type: string
      optional_param:
        required: false
        type: string
      other_optional_param:
        required: false
        type: string


jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: Print message
        run: echo "${{ inputs.message }}"
      - name: Print Vercel
        if: ${{ inputs.provider == 'vercel' }}
        run: echo "Provider is Vercel"
      - name: Print Netlify
        if: ${{ inputs.provider == 'netlify' }}
        run: echo "Provider is Netlify"
      - name: Optional Print
        if: ${{ inputs.optional_param || inputs.other_optional_param }}
        run: echo "Optional Print"
